name = "luminus"

compatibility_date = "2024-12-16"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "luminus-db"
database_id = "c886429a-af41-4f0f-a157-5a0e0c0a1049"

[[r2_buckets]]
binding = "R2"
bucket_name = "luminus-r2"

